timetracker/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('new_session', views.NewSessionView, name='new_session'),
    path('new_time_frame', views.NewTimeFrameView, name='new_time_frame'),
    path('take_screenshot', views.TakeScreenshotView, name='take_screenshot'),
    path('<int:pk>/', views.SessionDetailsView.as_view(), name='session_details'),
]

timetrackerchallenge/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from user import views

urlpatterns = [
    path('', views.LoginView.as_view(), name='login'),
    path('user/', include(('user.urls', 'user'), namespace='user')),
    path('timetracker/', include(('timetracker.urls', 'timetracker'), namespace='timetracker')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('<int:pk>/', views.ProfileView.as_view(), name='profile'),
]

timetracker/models.py
from __future__ import unicode_literals

import os

from django.db import models
from django.conf import settings
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

optional = {
    'blank': True,
    'null': True
}


class UserSession(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        to_field='email',
        related_name='user_sessions'
    )
    start = models.DateTimeField(_('session start time'), auto_now_add=True)
    end = models.DateTimeField('session end time', **optional)
    current = models.BooleanField(default=False)

    def __str__(self):
        if self.end:
            return f"{self.user.email}: {self.start} - {self.end}"
        return f"{self.user.email}: {self.start}"

    def get_current_time_frame(self):
        return TimeFrame.objects.filter(
            session__id=self.id,
            current=True
        ).first()


class TimeFrame(models.Model):
    session = models.ForeignKey(
        UserSession,
        on_delete=models.CASCADE,
        related_name='sessions_time_frames'
    )
    start = models.DateTimeField(_('start time'), auto_now_add=True)
    end = models.DateTimeField('end time', **optional)
    current = models.BooleanField(default=False)

    def __str__(self):
        if self.end:
            return f"{self.session.user.email}: {self.start} - {self.end}"
        return f"{self.session.user.email}: {self.start}"

    def save(self, *args, **kwargs):
        if not self.pk:
            current_tf = self.session.get_current_time_frame()
            if current_tf:
                current_tf.current = False
                current_tf.end = timezone.now()
                current_tf.save()
        return super(TimeFrame, self).save(*args, **kwargs)


class Screenshot(models.Model):
    time_frame = models.ForeignKey(
        TimeFrame,
        on_delete=models.CASCADE,
        related_name='time_frame_screenshots'
    )
    photo = models.ImageField(upload_to="screenshots", **optional)
    date_created = models.DateTimeField(_('date created'), auto_now_add=True)

    def __str__(self):
        return os.path.basename(self.photo.name)

user/models.py
from django.db import models
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.base_user import AbstractBaseUser
from django.utils.translation import gettext_lazy as _

from .managers import UserManager


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_('email address'), unique=True)
    full_name = models.CharField(_('full name'), max_length=30, blank=True)
    date_joined = models.DateTimeField(_('date joined'), auto_now_add=True)
    is_active = models.BooleanField(_('active'), default=True)
    is_staff = models.BooleanField(default=True)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def get_full_name(self):
        return self.full_name

user/forms.py
from django import forms


class LoginForm(forms.Form):
    """user login form"""
    email = forms.EmailField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Email',
        'required': True,
        'autofocus': True
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'Password',
        'required': True
    }))

timetracker/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.utils import timezone
from django.urls import reverse_lazy
from django.views.generic import DetailView

from .models import UserSession, TimeFrame
from .tasks import take_screenshots


def TakeScreenshotView(request):
    """
    Runs the 'take screenshot' task from celery
    """
    take_screenshots.delay()
    session = request.user.user_sessions.filter(current=True).first()
    return HttpResponseRedirect(
        reverse_lazy(
            'timetracker:session_details',
            kwargs={'pk': session.id}
        )
    )


def NewTimeFrameView(request):
    """
    Creates a new time frame
    """
    session = request.user.user_sessions.filter(current=True).first()
    TimeFrame.objects.create(session=session, current=True)
    take_screenshots.delay()
    return HttpResponseRedirect(
        reverse_lazy(
            'timetracker:session_details',
            kwargs={'pk': session.id}
        )
    )


def NewSessionView(request):
    """
    Creates a new session and timeframe
    """
    user = request.user

    update_data = {
        'current': False,
        'end': timezone.now()
    }
    UserSession.objects.filter(
        user__id=user.id,
        current=True
    ).update(**update_data)

    session = UserSession.objects.create(user=user, current=True)
    TimeFrame.objects.create(session=session, current=True)
    take_screenshots.delay()

    return HttpResponseRedirect(
        reverse_lazy(
            'timetracker:session_details',
            kwargs={'pk': session.id}
        )
    )


class SessionDetailsView(LoginRequiredMixin, DetailView):
    model = UserSession
    template_name = 'session_details.html'

    def get_context_data(self, **kwargs):
        context = super(SessionDetailsView, self).get_context_data(**kwargs)
        context['sessions_time_frames'] = self.object.sessions_time_frames.all().order_by('-start')
        return context

user/views.py
from django.contrib import messages
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic import DetailView
from django.views.generic.edit import FormView

from .forms import LoginForm
from .models import User


# Create your views here.
class LoginView(FormView):
    """login view"""

    form_class = LoginForm
    template_name = 'login.html'

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return HttpResponseRedirect(reverse_lazy(
                'user:profile',
                kwargs={'pk': self.request.user.pk}
            ))
        return super(LoginView, self).get(request, *args, **kwargs)

    def get_success_url(self, **kwargs):
        return reverse_lazy(
            'user:profile',
            kwargs={'pk': self.request.user.pk}
        )

    def form_invalid(self, form):
        for key, value in form.errors.items():
            for msg in value:
                messages.error(self.request, f"{key}: {msg}")
        return super(LoginView, self).form_invalid(form)

    def form_valid(self, form):
        """ process user login"""
        user = authenticate(username=form.cleaned_data['email'],
                            password=form.cleaned_data['password'])

        if user is not None:
            if user.is_active:
                login(self.request, user)
                self.request.session.set_expiry(1209600)
                return HttpResponseRedirect(self.get_success_url())
            else:
                messages.error(self.request, 'Please activate your account.')
        else:
            messages.error(self.request, 'Please check your credentials')

        return HttpResponseRedirect(reverse_lazy('login'))


class ProfileView(LoginRequiredMixin, DetailView):
    model = User
    template_name = 'user_profile.html'

    def get_context_data(self, **kwargs):
        context = super(ProfileView, self).get_context_data(**kwargs)
        context['user_sessions'] = self.object.user_sessions.all().order_by('-start')
        return context

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet"/>

    <!-- Local -->
    <link href="{% static 'css/custom.css' %}" rel="stylesheet" type="text/css">

    {% block css %}{% endblock %}

    <title>{% block title %}{% endblock %}</title>
  </head>

  <body>
    <div class="Container p-5">
      <main class="container-fluid ">
      {% block messages %}
        {% if messages %}
        <div id="message-container">
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
              {{ message }}
            </div>
            {% endfor %}
        </div>
        {% endif %}
      {% endblock %}

      {% block body %}{% endblock %}

      </main>
    </div>
  </body>

  <!-- Bootstrap -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

  <!-- jquery -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

  <!-- Local -->
  {% block js %}{% endblock %}

</html>

timetracker/templates/session_details.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Login {% endblock %}
{% block css %}
  <link href="{% static 'css/login.css' %}" rel="stylesheet" type="text/css">
{% endblock %}

{% block messages %}{% endblock %}

{% block body %}

    <div class="content">
        <div class="container">
            <h1>{{ user.email }}</h1>
                {% if object.current %}
                <a class="btn btn-outline-primary btn-rounded" role="button" href="{% url 'timetracker:take_screenshot'%}">Screenshot</a>
                <p class="fw-lighter fs-10 text">This will trigger an event that takes screenshots in 5 second intervals maximum of 5.</p>
                <a class="btn btn-outline-primary btn-rounded" role="button" href="{% url 'timetracker:new_time_frame'%}">New Time Frame</a>
                <p class="fw-lighter fs-10 text">This will create a new time frame and end the previous one </br> This will also automatically trigger the same screenshot functionality above.</p>
                {% endif %}

                <h4 class="mt-5">Time Frames</h4>

                <hr>
                {% for stf in sessions_time_frames %}
                <div class="accordion accordion-flush" id="accordionFlushExample">
                  <div class="accordion-item">
                    <h2 class="accordion-header" id="flush-headingOne">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">
                            <div class="container">
                                <div class="row align-items-start">
                                    <div class="col"><b>Start: </b> {{ stf.start }}</div>
                                    <div class="col"><b>End: </b> {{ stf.end }}</div>
                                </div>
                            </div>
                        </button>
                    </h2>
                    <div id="flush-collapseOne" class="accordion-collapse collapse" aria-labelledby="flush-headingOne" data-bs-parent="#accordionFlushExample">
                        <div class="accordion-body">
                            {% if stf.time_frame_screenshots.all %}
                            <table class="table mb-0 ms-5">
                                <tbody>
                                    {% for ss in stf.time_frame_screenshots.all %}
                                        <tr>
                                            <td>
                                                <!-- Button trigger modal -->
                                                <button
                                                    type="button"
                                                    class="btn btn-primary open-modal-btn"
                                                    data-bs-toggle="modal"
                                                    data-bs-target="#ss_modal"
                                                    data-url={{ss.photo.url}}
                                                    data-name={{ss}}>
                                                  {{ss}}
                                                </button>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                            {% endif %}

                        </div>
                    </div>
                  </div>
                </div>
                {% endfor %}

            </div>
        </div>
    </div>
    <!-- Vertically centered scrollable modal -->
    <div class="modal fade" id="ss_modal" aria-hidden="true">
      <div class="modal-dialog modal-xl">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">{{ss}}</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
                <img src="{{ss.photo.url}}" class="img-fluid">
          </div>
        </div>
      </div>
    </div>

{% endblock %}

{% block js %}
<script type="text/javascript" src="{% static 'js/screenshot.js' %}"></script>
{% endblock %}

timetracker/templates/user_profile.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Login {% endblock %}
{% block css %}
  <link href="{% static 'css/login.css' %}" rel="stylesheet" type="text/css">
{% endblock %}

{% block messages %}{% endblock %}

{% block body %}

    <div class="content">
        <div class="container">
            <h1>{{ user.email }}</h1>
            <div class="container mt-5">
                <div class="row align-items-start">
                    <div class="col"><h4>Sessions</h4></div>
                    <div class="col-2">
                    	<a class="btn btn-outline-primary btn-rounded" role="button" href="{% url 'timetracker:new_session'%}">New Session</a>
                    </div>
                </div>
            </div>
            <hr>
		    <table class="table table-hover" id="example">
		        <thead>
		            <tr>
		                <th>Start</th>
		                <th>End</th>
		                <th>Status</th>
		                <th></th>
		            </tr>
		        </thead>
		        <tbody>
		            {% for us in user_sessions %}
		            <tr>
		                <td>{{us.start}}</td>
		                <td>{{us.end}}</td>
		                <td>
		                	{% if us.current %}
							Current
							{% else %}
							Closed
							{% endif %}
		            	</td>
		                <td><a class="btn btn-outline-primary btn-rounded" role="button" href="{% url 'timetracker:session_details' us.id %}">Details</a></td>
		            </tr>
		            {% endfor %}
		        </tbody>
		    </table>
		</div>
    </div>

{% endblock %}

{% block js %}{% endblock %}

user/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Login {% endblock %}
{% block css %}
  <link href="{% static 'css/login.css' %}" rel="stylesheet" type="text/css">
{% endblock %}

{% block messages %}{% endblock %}

{% block body %}

    <div class="content">
        <div class="container">
            <form name="LoginForm" method="post">
                {% csrf_token %}
                {{ user.email }}
              <div class="form-row align-items-center">
                <div class="col-sm-3 my-1">
                  <label class="sr-only" for="inlineFormInputName">Email</label>
                  <input type="text" class="form-control" id="email" name="email" placeholder="Email">
                </div>
                <div class="col-sm-3 my-1">
                  <label class="sr-only" for="inlineFormInputName">Password</label>
                  <input type="password" class="form-control" id="password" name="password" placeholder="Password">
                </div>
                <div class="col-auto my-1">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
              </div>
            </form>
        </div>
    </div>

{% endblock %}

{% block js %}{% endblock %}